spring.application.name=SocialMediaApp

server.port=8090

spring.datasource.url=jdbc:postgresql://ep-gentle-scene-a1swtzzb.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FnD92prWteld

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true